In [1]:
import numpy as np


In [8]:
def match(a,b):
    l1=len(a)
    l2=len(b)
    i=0
    l=[0]
    while i<l1:
        if a[i]==b[i]:
            l.append(i)
        i=i+1
    del(l[0])    
    return l    
    
    

In [9]:
l=match(np.array([1,2,3,2,3,4,3,4,5,6]),np.array([7,2,10,2,7,4,9,4,9,8]))
print(l)

[1, 3, 5, 7]


In [10]:
def inv(arr):
    """
    Given an array arr (square matrix), find its inverse
    """
    # YOUR CODE HERE
    if(arr.shape[0]==arr.shape[1]):
      i=np.eye(arr.shape[0])
      return np.linalg.inv(arr)

In [11]:
print(inv(np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [15]:
def lin_eqn(a,b):
    return np.matmul(np.linalg.inv(a),b)
    


In [16]:
x=lin_eqn(np.array([[1.0, 2.0], [3, 4]]),np.array([8.0,  18.0]))
print(x)

[2. 3.]
