In [1]:
import numpy as np

In [2]:
#matching
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
c=[]
asize=np.size(a)
def match(a,b):
    for i in range(0,asize):
        if (a[i]==b[i]):
            c.append(i)
    return c
print(match(a,b))
    

[1, 3, 5, 7]


In [3]:
#inverse of matrix
I=np.eye(3)
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
def inv(arr):
    C=I/A 
    return C
    
print(A)

print(inv(A))


[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.16666667  0.          0.        ]
 [ 0.         -0.5         0.        ]
 [ 0.          0.          0.14285714]]


In [4]:
#x+2y=8
#3x+4y=18
#AX=B
#X=B*A_inverse
#X=np.array[[x],[y]]

A=np.matrix([[1,2],[3,4]])
B=np.matrix([[8],[18]])
def lin_eqn(a,b):
    x=np.linalg.inv(a)*b
    return x
print(lin_eqn(A,B))

    

[[2.]
 [3.]]


In [5]:
#rank of a matrix
A=np.matrix([[4, 2, 6, 0, 8], [7, 9, 3, 5, 1]])
def rank(a):
    x=np.linalg.matrix_rank(a)
    return x
print(rank(A))

2


In [6]:
#shuffle
#axis=0:down
#axis=1:across
A=np.array([[1,2,3,4,5],[6,7,8,9,10]])

def shuf(a):
    x=np.vstack([a[1],a[0]])
    return x
print(A)
print(shuf(A))    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [14]:
#windows and stride 
A=[1,3,7,1,2,6,0,1]
window_len=4
stride_len=2
a=np.array(A)
i=0
b=[]
while i+window_len<=len(a):
    b.append(a[i:i+window_len])
    i=i+stride_len
b=np.array(b)

print(b)

        
    


        
        

[[1 3 7 1]
 [7 1 2 6]
 [2 6 0 1]]
