In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("BostonHousing.csv")

In [3]:
df.shape

(506, 14)

In [4]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [5]:
%matplotlib inline

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
data = df.values

In [8]:
print(data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


In [9]:
sc = StandardScaler()

In [10]:
data[:,:-1] = sc.fit_transform(data[:,:-1])

In [11]:
data

array([[-0.41978194,  0.28482986, -1.2879095 , ...,  0.44105193,
        -1.0755623 , 24.        ],
       [-0.41733926, -0.48772236, -0.59338101, ...,  0.44105193,
        -0.49243937, 21.6       ],
       [-0.41734159, -0.48772236, -0.59338101, ...,  0.39642699,
        -1.2087274 , 34.7       ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.98304761, 23.9       ],
       [-0.40776407, -0.48772236,  0.11573841, ...,  0.4032249 ,
        -0.86530163, 22.        ],
       [-0.41500016, -0.48772236,  0.11573841, ...,  0.44105193,
        -0.66905833, 11.9       ]])

In [12]:
print(data.shape)

(506, 14)


In [13]:
X=data[:,:-1].copy()

In [14]:
Y=data[:,-1].copy()

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y)

In [17]:
print(X_train.shape, Y_train.shape)

(379, 13) (379,)


In [18]:
Y_train=Y_train.reshape(-1,1)

In [19]:
Y_test=Y_test.reshape(-1,1)

In [20]:
print(X_test.shape, Y_test.shape)

(127, 13) (127, 1)


In [21]:
X_train=X_train.T

In [22]:
X_test=X_test.T

In [23]:
Y_train=Y_train.T
Y_test=Y_test.T

In [24]:
def compute_cost(y,y_hat):
    return np.sqrt(np.sum(((y_hat-y)**2), axis = 1)/y.shape[1])

In [25]:
# Method 1
def compute_w1(X,Y):
    X=X.T
    Y=Y.T
    w = np.linalg.inv(np.dot(X.T,X)).dot(np.dot(X.T,Y))
    return w.T

In [26]:
def add_row_1(arr):
    ones = np.ones((1,arr.shape[1]))
    arr= np.concatenate((arr, ones), axis=0)
    return arr

In [27]:
X_train_1=add_row_1(X_train)
print(X_train.shape)

(13, 379)


In [28]:
print(X_train)

[[-0.38297076 -0.4041053  -0.3946686  ... -0.4053214  -0.39560307
  -0.4169692 ]
 [-0.48772236 -0.48772236 -0.48772236 ... -0.48772236  0.45650813
   1.87285388]
 [ 1.56899549  0.40609801 -0.16440754 ... -0.16440754 -0.76993132
  -1.07342276]
 ...
 [ 1.26893833 -1.13534664 -0.30309415 ... -0.30309415  0.29797709
  -0.39556665]
 [ 0.23656665  0.44105193  0.44105193 ... -0.19784123  0.22362871
   0.34314021]
 [ 0.59530919  0.44672498  0.62194221 ...  0.3808433  -1.27040386
  -1.1274266 ]]


In [29]:
X_test_1 = add_row_1(X_test)

In [30]:
print(X_test.shape)
print(X_test)

(13, 127)
[[ 0.25724145 -0.41068737 -0.39119253 ... -0.41714376 -0.15281243
   0.6662794 ]
 [-0.48772236 -0.48772236 -0.48772236 ...  1.22906036 -0.48772236
  -0.48772236]
 [ 1.01599907 -1.03402724 -0.07978012 ... -1.44257341  1.2319449
   1.01599907]
 ...
 [ 0.80657583 -0.85792914  0.06679585 ...  0.57539459 -1.73641788
   0.80657583]
 [ 0.44105193  0.40081274  0.35914818 ...  0.36375321 -0.65330068
  -3.24494606]
 [-0.26816131 -0.42235247  0.75791078 ... -0.94800416 -0.21769875
   1.60175696]]


In [31]:
print(X_test_1.shape,X_train_1.shape)

(14, 127) (14, 379)


In [32]:
w1=compute_w1(X_train_1, Y_train)

In [33]:
print(w1)

[[-1.2927231   1.45024146  0.23426086  0.35829975 -1.83507368  2.59069871
  -0.0978473  -3.14573161  3.02861544 -2.47324161 -1.80819031  1.00842526
  -3.68977134 22.40462055]]


In [34]:
print(w1.shape)

(1, 14)


In [35]:
Y_hat_1 = w1.dot(X_train_1)

In [36]:
cost1 = compute_cost(Y_train, Y_hat_1)

In [37]:
print(cost1)

[4.44317704]


In [38]:
print(Y_train)

[[17.4 20.3 18.7 15.4 27.1 22.8 13.1 24.4 32.  13.2 22.9 21.2 11.  19.4
  22.6 22.1 15.3 15.6 13.8 30.5 19.7 22.4 22.3 22.  24.3 20.6 17.5 48.8
  10.4 23.4 31.6 23.  14.5 18.  27.1 50.  21.  23.6 24.7 19.9 31.  16.5
  22.6 23.5 21.7 21.6 20.1 50.  20.9 23.7 30.1 10.4 22.5 46.  36.  21.4
  17.1  8.7 10.5 14.2 23.3 17.1 19.4 13.8 21.7 19.1 23.3 24.2 22.7 20.9
  24.1 28.4 19.2 18.2 19.9 17.2 21.2  8.8 20.  18.7 16.2 24.6 28.6 26.6
  20.1 18.9 21.7 16.8 29.1 24.  35.2 11.8 14.1  7.2 18.6 25.   9.7 18.5
  13.4 31.5 33.1 19.6 18.3 16.1 19.3 15.  28.4 21.1 35.1  8.1 20.3 22.2
  24.7 36.2 33.2 20.8 23.7 20.8 20.   5.  21.9 15.2 21.7 26.2 34.9 20.7
  24.4 13.4 13.1 20.5 19.5 19.7 13.5 19.5 25.  17.2 33.4 30.1 10.2 21.6
  13.1 48.3 19.8 20.1 23.1 19.6 17.8 18.4 21.9 15.4 21.4 13.8 24.4 30.8
  27.5 13.6 23.2 25.  21.2 14.3 32.4 50.  11.3 23.3 23.1 20.6 18.5 21.
  32.  24.5 29.6 19.1 33.3 22.2 12.  16.8 17.5 19.3 24.8 21.9 22.  11.5
  21.4 20.6 21.8 17.6 41.3 23.1 19.6 27.5 22.9 12.6  7.2 27.  18.

In [39]:
print(Y_hat_1)

[[16.13895101 19.18699451 20.36691718 18.20489934 19.19035566 26.10870947
  20.42116501 28.74166757 33.26467416  8.79156417 25.27766848 21.38262378
  14.03799372 17.07643566 23.60038082 26.87460679 18.92317849 12.19892852
   0.88192346 30.10212988 21.3569996  23.79161876 27.56982571 27.24586195
  28.38388651 27.38197691 18.57617191 40.4920642   6.0457546  24.02115721
  33.9524157  20.20390234 13.96635575 19.1430024  26.88922764 42.79271942
  20.89896267 28.65836526 23.10556719 20.32719094 34.10702836 11.28413639
  22.87059558 30.97787696 20.78459098 25.41736135 23.7589989  43.91049192
  22.28857926 11.46646836 26.42215559 11.0243975  29.3114331  38.68955453
  36.08735846 24.34148713 19.55204678  8.18425026 12.4854254  18.29134955
  25.39947141 20.12420158 26.19304497 11.69947761 21.90997444 23.65645263
  25.35129591 25.16735376 21.3896452  20.71316506 20.69812872 31.31456924
  23.34735129 15.62509304 19.35586998 16.05219496 23.07004379  3.13136792
  22.52870406 21.75340682 15.49111031 

In [40]:
from sklearn.linear_model import LinearRegression

In [41]:
lin_reg = LinearRegression()

In [42]:
print(Y_train.shape)
lin_reg.fit(X_train.T,Y_train.T)

(1, 379)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [43]:
from sklearn import metrics

In [44]:
print(np.sqrt(metrics.mean_squared_error(Y_train, Y_hat_1)))

4.44317703930745


In [45]:
y_pred_1=lin_reg.predict(X_train.T)
y_pred_1=y_pred_1.T

In [46]:
print(np.sqrt(metrics.mean_squared_error(Y_train, y_pred_1)))

4.44317703930745


In [47]:
print(y_pred_1.shape)

(1, 379)


In [48]:
data2 = df.values

In [49]:
X2=data[:,:-1].copy()
Y2=data[:,-1].copy()

In [52]:
X_train_2, X_test_2, Y_train_2, Y_test_2 = train_test_split(X2,Y2)

In [56]:
y_pred_test = lin_reg.predict(X_test.T)

In [54]:
print(X_test_1.shape)

(14, 127)


In [55]:
print(X_test.shape)

(13, 127)


In [57]:
print(np.sqrt(metrics.mean_squared_error(Y_test, y_pred_test.T)))

5.4473815605858755
