In [3]:
def last_element(l):
    """
    Returns last element of list l
    """
    # YOUR CODE HERE
    print (l[-1])
last_element([1])
last_element(["Hello", "World"])

1
World


In [6]:
def num_elements(l):
    """
    Returns number of elements in the list l
    """
    # YOUR CODE HERE    
    print(len(l))

num_elements([2, 3, 4])


3


In [7]:
def reverse_list(l):
    """
    Returns the reverse of a list l
    """
    # YOUR CODE HERE
    l.reverse()
    print(l)

reverse_list([2, 3, 4])


[4, 3, 2]


In [11]:
def is_palindrome(l):
    """
    Returns True if l is a palindrome, False otherwise
    """
    # YOUR CODE HERE  
    lr=l.copy()
    l.reverse()
    if list(l)==list(lr):
        print("True")
    else:
        print("False")

is_palindrome([1, 2, 1])
is_palindrome([1, 2, 3, 2, 1])
is_palindrome([1, 2, 3, 4])


True
True
False


In [17]:
def compress(l):
    """
    Returns a list with consecutive duplicate elements replaced by a single element
    """
    # YOUR CODE HERE
    i=0
    while i < len(l)-1:
        if l[i]==l[i+1]:
            del l[i]
        else:
            i=i+1
    print(l)

compress([1, 2, 2])
compress([1, 2, 2, 2, 1, 1, 3, 'x', 'x', 'x'])


[1, 2]
[1, 2, 1, 3, 'x']


In [18]:
def slice(l, i, k):
    """
    Returns a list containing the elements between i'th and k'th elements of original list l.
    """  
    # YOUR CODE HERE
    print(l[i:k])

slice([1, 3, 8, 9, 7], 1, 3)  
slice([1, 4, 6, 'x', 9, 0], 2, 10)

[3, 8]
[6, 'x', 9, 0]


In [19]:
def insert_element(l, i, elem):
    """
    Returns a new list containing elem at index i. If i > len (l), insert element at the end of the list
    """      
    # YOUR CODE HERE
    l.insert(i, elem)
    print(l)

insert_element([1, 2, 3, 4], 2, 5)
insert_element([1, 5], 3, 5)


[1, 2, 5, 3, 4]
[1, 5, 5]


In [20]:
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], [5, 7, 8, 3, 5, 6, 3, 7, 2, 12, 5, 7, 2, 6, 9, 2], "-", color="orange")
plt.title("Epic Info")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.show()
#How do I get the grey background?


<Figure size 640x480 with 1 Axes>

In [36]:
def match(a,b):
    '''
    Inputs:
      a, b: numpy arrays of same shape of 1 dimension
    Outputs:
      list containing indices where both arrays have same elements
    '''
    # YOUR CODE HERE
    print(set(a) & set(b))
match([1, 2, 3, 2, 3, 4, 3, 4, 5, 6], [7, 2, 10, 2, 7, 4, 9, 4, 9, 8])


{2, 4}


In [37]:
import numpy as np
def inv(arr):
    """
    Given an array arr (square matrix), find its inverse
    """
    # YOUR CODE HERE
    iarr=np.linalg.inv(arr)
    print(iarr)

inv([[6, 1, 1], [4, -2, 5], [2, 8, 7]])    

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [40]:
def lin_eqn(a,b):
    '''
    Solve the system of linear equations
    of the form ax = b
    
    Eg. 
    
    Solve the system of linear equation
    
    x + 2*y = 8
    3*x + 4*y = 18
    
    Given inputs a and b represent coefficients and constant of linear equation respectively
    
    coefficients: 
    a = np.array([[1, 2], [3, 4]]) 
    
    constants: 
    b = np.array([8, 18])
    
    Desired Output: [2,3]
    

    '''
    # YOUR CODE HERE
    c=np.linalg.inv(a)
    sol=c*b
    print(sol)

lin_eqn([[1, 2], [3, 4]], [8, 18])


[[-16.  18.]
 [ 12.  -9.]]


In [45]:
import numpy as np
def rankArray(arr):
    sarr=sorted(arr)
    rarr=[sarr.index(i) for i in arr]
    print(rarr)

rankArray([9, 4, 15, 0, 17])


[2, 1, 3, 0, 4]
